### ISSUE TITLE
Suggestion for JSX

### ISSUE THREAD

**Issue by samchamberland** [pawelgrzybek/bimbo-theme#11]
Hi Pawel,

I noticed a little issue while using the theme. I suspect the use of the `meta.tag` scope [here](https://github.com/pawelgrzybek/bimbo-theme/blob/master/themes/bimbo-theme-color-theme.json#L322) causes the problem.

For example, in the screenshot below, the `name` key should be gray, just like the `msgText` key.
The `Message => ` part should also be gray (it currently displays as gray in HTML)
Current:
<img width="652" alt="screen shot 2018-03-01 at 5 40 30 pm" src="https://user-images.githubusercontent.com/20142959/36874092-9ec1a2e6-1d78-11e8-9517-62a2f30b9dad.png">

When I add the following customization to my config file, it fixes the issues:
```
  "editor.tokenColorCustomizations": {
    "[Bimbo Theme]": {
      "textMateRules": [
        {
          "scope": "meta.tag",
          "settings": {
            "foreground": "#D4D4D4"
          }
        }
      ]
    }
  },
```
Result: 
<img width="662" alt="screen shot 2018-03-01 at 5 40 45 pm" src="https://user-images.githubusercontent.com/20142959/36874102-a8ca3960-1d78-11e8-8813-264e02178021.png">

Let me know what you think, I can submit a PR if you like the suggestion.

**Comment by pawelgrzybek** [comment]
Hi.

Thanks for spot.  Yeah. PR would be amazing! I am planing to redefine and simplify Bimbo schemes and release 2.0. All the suggestions are very welcome.

Thanks again!

**Comment by samchamberland** [comment]
Great. I'm on it.
Thank you for this beautiful theme!

**Comment by pawelgrzybek** [comment]
WOW!

I am happy to have at least one happy user of it :)
If you want to we can collaborate and deliver 2.0 together. Would you be interested to listen to my wishlist one day and help me to develop that?

Thanks a ton and have a great weekend :)

**Comment by pawelgrzybek** [comment]
All done. The update should be ready to download for you, me and all the happy bibo users :)

**Comment by samchamberland** [comment]
I will gladly help for a 2.0 release! 
Being a long term Sublime Text user (and Oceanic Next / Boxy Ocean) myself, your theme definitely eased my migration to VSCode more than I'd like to admit :]
