### ISSUE TITLE
how do i get font-family like in that picture of bimbo theme

### ISSUE THREAD

**Issue by rohyadav** [pawelgrzybek/bimbo-theme#5]
how do i get font-family like in that picture of bimbo theme

![bimbo-theme-1](https://user-images.githubusercontent.com/21152844/28491225-dc54d99c-6f0a-11e7-88cd-5ca0a599ac85.jpg)

**Comment by pawelgrzybek** [comment]
Hi.

Hi it is a global editors settings. It has nothing to do with a theme. Read more about it [here](https://code.visualstudio.com/docs/getstarted/settings) and [this is the line](https://github.com/pawelgrzybek/dotfiles/blob/master/VSCode/settings.json#L3) that is responsible for a font that I'm using in my editor. The font that I use is Operator Monto that you can but [here](https://www.typography.com/blog/introducing-operator).

Have a great day 🥑
