### ISSUE TITLE
Adding cursive for React Props [feature]

### ISSUE THREAD

**Issue by Pszek** [pawelgrzybek/bimbo-theme#6]
Thanks for a great extension of the Oceanic Next theme. Adding a cursive for React props would be the icing on the cake.

**Comment by pawelgrzybek** [comment]
Can be done :) Thanks for a nice suggestion :)

**Comment by pawelgrzybek** [comment]
If you like the theme and the work that I put to make it, I will appreciate if you retweet this blogpost as a payback :)

https://pawelgrzybek.com/i-built-a-thing-bimbo-theme-for-visual-studio-code/

Thanks

**Comment by Pszek** [comment]
@pawelgrzybek Would love to, but I am not very social (as you can see, I obfuscate my real name behind hanzi (so companies I work with won't have any complaints that this is a fake account - 'It's my real name; just transcripted to Chinese)), so I don't have a Twitter account. But I can buy you a beer when you will be (back?) in Warsaw.

**Comment by pawelgrzybek** [comment]
Hahah I'm in Warsaw in 3 weeks :)

**Comment by Pszek** [comment]
Artezan/Ceska/Jabberwocky/Gorączka Złota :wink ? (Welcome other suggestions)

**Comment by Pszek** [comment]
@pawelgrzybek the offer is still open ;)

**Comment by wmertens** [comment]
I can join you guys too :)

**Comment by pawelgrzybek** [comment]
Hi dudes!

I'm Warsaw 2017.08.30 - 2017.09.03. I'm more than happy to hook for a beer with you all 🍻
Props are italic now by the way (and some more tiny improvements).

Hopefully to see you all very soon :)

**Comment by wmertens** [comment]
Aww, I'm out of the country then :( Some other time!

**Comment by Pszek** [comment]
@pawelgrzybek It is the time I will be probably moving, so no. I hoped for an earlier date :(
