### ISSUE TITLE
Add Italic to HTML attributes

### ISSUE THREAD

**Issue by Puertas** [pawelgrzybek/bimbo-theme#8]
Hi,

First of all thanks a lot for the theme, is awesome.

I think that it would be a nice addition to use italic on the HTML attributes, as use to be in the original Oceanic Next theme. It looks very neat with Operator Mono, a little screenshot to illustrate:

<img width="422" alt="captura de pantalla 2017-08-08 a las 10 27 34" src="https://user-images.githubusercontent.com/1136445/29062998-552bb87e-7c24-11e7-8a3e-725bfdcf29cd.png">

Again thanks.

Kr,
Jose

**Comment by pawelgrzybek** [comment]
Hi :)

I like this suggestion a lot. I'm currently working slowly on some minor colour amendments to improve selected text and search highlighting. I'll definitely add italics to HTML attributes and React JSX props as suggested by another happy user.

Thanks for your input and amazing feedback! Im really glad that you enjoy your code editor with Bimbo :)

Have a great day!
